### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by damotta1** [zotify-dev/zotify#100]
After typing in my username and password, I'm getting the following message:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='apresolve.spotify.com', port=443): Max retries exceeded with url: /?type=accesspoint (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CF36E4EDB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

Any idea what is wrong?

**Comment by Jake4353** [comment]
could be a rate limit or maybe ban

**Comment by darrenhaken** [comment]
Did you ever fix it? I have the same problem

**Comment by Kezzsim** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/zotify/__main__.py", line 68, in <module>
    main()
  File "/app/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/app/zotify/app.py", line 21, in client
    Zotify(args)
  File "/app/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
  File "/app/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 1623, in create
    session = Session(
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 904, in __init__
    self.connection = Session.ConnectionHolder.create(address, None)
  File "/usr/local/lib/python3.9/site-packages/librespot/core.py", line 1864, in create
    sock.connect((ap_address, ap_port))
ConnectionRefusedError: [Errno 111] Connection refused
```

I also cannot create a credential because of this error sadly, slightly different stack trace though. Perhaps something upstream in Librespot I can look into.
