### ISSUE TITLE
"json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 128)"

### ISSUE THREAD

**Issue by MichelTGM** [zotify-dev/zotify#117]
I cannot for the life of me figure out how to fix this.
this is the full error
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\miche\.local\bin\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\miche\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\miche\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
  File "C:\Users\miche\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 20, in __init__
    Zotify.CONFIG.load(args)
  File "C:\Users\miche\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\config.py", line 106, in load
    jsonvalues = json.load(config_file)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miche\scoop\apps\python\3.12.2\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\miche\scoop\apps\python\3.12.2\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miche\scoop\apps\python\3.12.2\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\miche\scoop\apps\python\3.12.2\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 128)`
please help me

**Comment by Laivum** [comment]
I also have this error, word for word, except the very last line reads as:

json.decoder.JSONDecodeError: Invalid \escape: line 3 column 32 (char 65)

I am just a little noob who doesn't know code.

**Comment by FFGamer04** [comment]
I also have the same error. Has anyone found a solution?

**Comment by DinkFloyp** [comment]
never had that error so no idea ...
just one hint though :  in my case that decode.py file is located in C:\Users\********\scoop\apps\python\3.12.4\Lib\json
vs. yours in ..........python\3.12.2\lib.................
=> I would suggest : try to update Python (or just that json library maybe) to a more recent or latest version

**Comment by FFGamer04** [comment]
Nah found the problem, in the `config.json` file I had written my download path with only one `\` (`C:\Example\example1`), which caused an error, fixed by simply replacing with `\\` (`C:\\Example\\example1` ) @MichelTGM @Laivum Please check if this fixes your issues
