### ISSUE TITLE
liked songs download option error

### ISSUE THREAD

**Issue by KeshavGittiup** [zotify-dev/zotify#132]
PS C:\Users\DELL> zotify -l
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\dell\.local\bin\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\DELL\pipx\venvs\zotify\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\DELL\pipx\venvs\zotify\Lib\site-packages\zotify\app.py", line 56, in client
    for song in get_saved_tracks():
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 32, in get_saved_tracks
    songs.extend(resp[ITEMS])
                 ~~~~^^^^^^^
KeyError: 'items'
PS C:\Users\DELL>

**Comment by kirkpsmith** [comment]
I had an empty line at the end of my `archive` plaintext file which contains the songs already downloaded. Removing the line solved this for me.
