### ISSUE TITLE
[Bug] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yodaluca23** [zotify-dev/zotify#143]
I get this error on the 128th song when running ```zotify https://open.spotify.com/playlist/6U7CJSEwgsrb41wXEPcr96 --output "{playlist}/{artist} - {song_name}.{ext}"```

Error:

```Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.10.4/bin/zotify", line 8, in <module>
    sys.exit(main())
  File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/zotify/app.py", line 48, in client
    download_from_urls(args.urls)
  File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/site-packages/zotify/app.py", line 108, in download_from_urls
    if not song[TRACK][NAME] or not song[TRACK][ID]:
TypeError: 'NoneType' object is not subscriptable```

**Comment by yodaluca23** [comment]
Oh, here is config file too

```
{
    "SAVE_CREDENTIALS": "True",
    "CREDENTIALS_LOCATION": "/Users/username/Library/Application Support/Zotify/CREDENTIALS",
    "OUTPUT": "",
    "SONG_ARCHIVE": "",
    "ROOT_PATH": "",
    "ROOT_PODCAST_PATH": "",
    "SPLIT_ALBUM_DISCS": "False",
    "DOWNLOAD_LYRICS": "False",
    "MD_SAVE_GENRES": "False",
    "MD_ALLGENRES": "False",
    "MD_GENREDELIMITER": ",",
    "DOWNLOAD_FORMAT": "AAC",
    "DOWNLOAD_QUALITY": "high",
    "TRANSCODE_BITRATE": "auto",
    "SKIP_EXISTING": "True",
    "SKIP_PREVIOUSLY_DOWNLOADED": "False",
    "RETRY_ATTEMPTS": "1",
    "BULK_WAIT_TIME": "1",
    "OVERRIDE_AUTO_WAIT": "False",
    "CHUNK_SIZE": "20000",
    "DOWNLOAD_REAL_TIME": "False",
    "LANGUAGE": "en",
    "PRINT_SPLASH": "True",
    "PRINT_SKIPS": "True",
    "PRINT_DOWNLOAD_PROGRESS": "True",
    "PRINT_ERRORS": "True",
    "PRINT_DOWNLOADS": "False",
    "PRINT_API_ERRORS": "True",
    "PRINT_PROGRESS_INFO": "True",
    "PRINT_WARNINGS": "True",
    "TEMP_DOWNLOAD_DIR": ""
}
```

**Comment by Googolplexed0** [comment]
Fixed on [my fork](https://github.com/Googolplexed0/zotify) just now. If you don't want to deal with my changes/upgrades, I think you could fix this by replacing app.py line 108 with:
```py
if song[TRACK] is None or not song[TRACK][NAME] or not song[TRACK][ID]:
```

**Comment by yodaluca23** [comment]
Thank you, I will have to try it.

**Comment by yodaluca23** [comment]
> Fixed on [my fork](https://github.com/Googolplexed0/zotify) just now. If you don't want to deal with my changes/upgrades, I think you could fix this by replacing app.py line 108 with:
> 
> ```python
> if song[TRACK] is None or not song[TRACK][NAME] or not song[TRACK][ID]:
> ```

Can confirm, your fork fixes it! I see you also have a bunch of other changes, when do you plan to make a PR?

**Comment by Googolplexed0** [comment]
I've been making tweaks here and there for a year or two and over time they have built up. I finally got around to cleaning it up a bit to get it worthy of being public. Would be fine with a PR whenever, but the contribution docs are pretty clear about not wanting multiple changes at once.

**Comment by willmaddrey** [comment]
@Googolplexed0 Thanks for the plug of your fork, fixed a  bunch of issues I was having with zotify!

**Comment by yodaluca23** [comment]
@Googolplexed0 I noticed that Spotify must've changed their API or something, it no longer correctly decodes quotes, periods, and some other things in song and album names, since it doesn't look like main will be updated for a while, I was wondering if you could try to fix it?

Example Songs:
https://open.spotify.com/track/3qrH2YFnbEiQeUe4wzgOuP
https://open.spotify.com/track/72jCZdH0Lhg93z6Z4hBjgj
https://open.spotify.com/track/5ZkAx8zjLiSs1nMmBwJoZS

**Comment by Googolplexed0** [comment]
> @Googolplexed0 I noticed that Spotify must've changed their API or something, it no longer correctly decodes quotes, periods, and some other things in song and album names, since it doesn't look like main will be updated for a while, I was wondering if you could try to fix it?
> 
> Example Songs:
> https://open.spotify.com/track/3qrH2YFnbEiQeUe4wzgOuP
> https://open.spotify.com/track/72jCZdH0Lhg93z6Z4hBjgj
> https://open.spotify.com/track/5ZkAx8zjLiSs1nMmBwJoZS

I can definitely take a look in the next couple of days. If it really is an API issue it may be beyond my control, but my guess is that it's just a small formatting change somewhere. If you copy/paste an issue onto my fork it will be much easier for me to track.

**Comment by yodaluca23** [comment]
> If you copy/paste an issue onto my fork it will be much easier for me to track.

Issues are disabled, otherwise I would've.

**Comment by Googolplexed0** [comment]
> Issues are disabled, otherwise I would've.

Didn't notice that was the case, I did not do that manually so not sure why they were turned off... Should be fixed now?
