### ISSUE TITLE
[bug]  Podcast episode not downloading

### ISSUE THREAD

**Issue by thegreatestgiant** [zotify-dev/zotify#148]
https://open.spotify.com/episode/66G6eaHjnQurhyThOXs3ha?si=c5c7c5a7ad104405
This episode of Eda's Requim isn't downloading
I get this error, everything else works just fine

```sh
zotify https://open.spotify.com/episode/66G6eaHjnQurhyThOXs3ha?si=c5c7c5a7ad104405
        [●∙∙] Preparing download... Couldn't resolve redirect!                                                                                        
        [∙●∙] Preparing download... Traceback (most recent call last):
  File "/home/sean/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/app.py", line 48, in client
    download_from_urls(args.urls)
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/app.py", line 125, in download_from_urls
    download_episode(episode_id)
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/podcast.py", line 96, in download_episode
    stream = Zotify.get_content_stream(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 742, in load
    return self.load_episode(playable_id, audio_quality_picker,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 773, in load_episode
    return CdnFeedHelper.load_episode_external(self.__session, episode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 368, in load_episode_external
    streamer = session.cdn().stream_external_episode(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 429, in stream_external_episode
    return CdnManager.Streamer(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 578, in __init__
    response = self.request(range_start=0,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 639, in request
    raise IOError(response.status_code)
OSError: 403
```

**Comment by JaimeVadell** [comment]
> https://open.spotify.com/episode/66G6eaHjnQurhyThOXs3ha?si=c5c7c5a7ad104405 This episode of Eda's Requim isn't downloading I get this error, everything else works just fine
> 
> ```shell
> zotify https://open.spotify.com/episode/66G6eaHjnQurhyThOXs3ha?si=c5c7c5a7ad104405
>         [●∙∙] Preparing download... Couldn't resolve redirect!                                                                                        
>         [∙●∙] Preparing download... Traceback (most recent call last):
>   File "/home/sean/.local/bin/zotify", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/__main__.py", line 64, in main
>     args.func(args)
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/app.py", line 48, in client
>     download_from_urls(args.urls)
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/app.py", line 125, in download_from_urls
>     download_episode(episode_id)
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/podcast.py", line 96, in download_episode
>     stream = Zotify.get_content_stream(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/zotify/zotify.py", line 53, in get_content_stream
>     return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 742, in load
>     return self.load_episode(playable_id, audio_quality_picker,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 773, in load_episode
>     return CdnFeedHelper.load_episode_external(self.__session, episode,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 368, in load_episode_external
>     streamer = session.cdn().stream_external_episode(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 429, in stream_external_episode
>     return CdnManager.Streamer(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 578, in __init__
>     response = self.request(range_start=0,
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/sean/.local/pipx/venvs/zotify/lib/python3.11/site-packages/librespot/audio/__init__.py", line 639, in request
>     raise IOError(response.status_code)
> OSError: 403
> ```

Having the same issue with some particular podcasts.

**Comment by mmaterowski** [comment]
Same for me for this podcast https://open.spotify.com/episode/23wxZblaSN2AGiySe94wJl
