### ISSUE TITLE
Errors: "bad escape \m at position 3" and "[WinError 183] Cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by danthi123** [zotify-dev/zotify#151]
Had the first mentioned error and once fixed, had the second. Used ChatGPT to troubleshoot and fix both so someone may want to review. Sorry I don't know the etiquette or process here but wanted to give my fixes in case anyone else would benefit.

### First error

```
bad escape \m at position 3

Traceback (most recent call last):
  File "C:\Users\dant123\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 190, in download_track
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 544, in _parse
    code = _escape(source, this, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\re\_parser.py", line 443, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \m at position 3
```

### Solution for first error

In line 190 of the file track.py (wherever you installed Zotify to, can use the program Everything to find easily on Windows):

Replace

`c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1`

with

`c = len([file for file in Path(filedir).iterdir() if re.search(fr'^{re.escape(str(filename))}_', str(file))]) + 1`

### Second error

```
[WinError 183] Cannot create a file when that file already exists: '_path to audio file_' -> '_path to other audio file_'

Traceback (most recent call last):
    File "_path to track.py_", line 270, in download_track
        Path(filename_temp).rename(filename)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1363, in rename
    os.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '_path to audio file_' -> '_path to other audio file_'
```

### Solution for the second error

In line 269 of same the track.py file:

Replace

Path(filename_temp).rename(filename)

with

```python
if Path(filename).exists():
    # Decide how to handle the existing file
    # For example, delete it or rename filename_temp differently
    Path(filename).unlink()  # Example: delete existing file
    Path(filename_temp).rename(filename)  # Rename filename_temp to filename
else:
    Path(filename_temp).rename(filename)  # Rename filename_temp to filename
```

**Comment by FISSI0N** [comment]
I recommend to not follow chatGPTs advice.

doing the first causes some songs to keep their temporary name ._1.mp3 which then causes the other issue.
I haven't looked further into the second error but have my doubts that it properly fixes the issue and renames the file
