### ISSUE TITLE
BadCredentials

### ISSUE THREAD

**Issue by ryanmilley** [zotify-dev/zotify#167]
I think logins are broken. 

Password:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ryan\scoop\apps\python\current\Scripts\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "C:\Users\Ryan\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

**Comment by qun-media** [comment]
Can confirm I’m getting the same error. Tried logging in with username, email and also tried changing my password. Deleting the credentials file didn’t help and also login in through the arguments didn’t change anything

**Comment by tig3rmast3r** [comment]
there is an issue with librespot login, still not solved as far as i can see on their git
https://github.com/librespot-org/librespot/issues/1308

**Comment by ryanmilley** [comment]
> there is an issue with librespot login, still not solved as far as i can see on their git [librespot-org/librespot#1308](https://github.com/librespot-org/librespot/issues/1308)

ah, yeah seems to be..thanks. I'll leave it up for other people to see

**Comment by ryanmilley** [comment]
it's working again now.

**Comment by ImranR98** [comment]
Same here

**Comment by AJK-King** [comment]
same here

**Comment by rkmfl** [comment]
Same issue. Repeating the error returned to help other users locate this thread:
#### librespot.core.Session.SpotifyAuthenticationException: BadCredentials

**Comment by 123Sanyam123** [comment]
Anyone find a fix yet?

**Comment by 11plustwo** [comment]
I'm having this issue too. I'm new to Zotify, but I tried on Windows 10 and macOS Ventura and got the same error on each.

**Comment by ImranR98** [comment]
> Do the devs get notified if we comment on a closed ticket?

Yes, unless they manually unsubscribe from the issue (or have disabled emails in general).

There is already open issue #174 anyways.

**Comment by 0bscurianx** [comment]
the issue still remains, there seems to be some problem with the credentials.json file

**Comment by caoilainnl** [comment]
How to get the credentials on Mac https://github.com/zotify-dev/zotify/issues/181#issuecomment-2428102939 (It might work for any OS actually)

Using the Oauth method

**Comment by oryx-taker** [comment]
Having the same issue, inicially I could use zotify (I had my user and password from a long time ago saved), later I had to change my password and I couldn't make zotify work again.

**Comment by GreenEllipsis** [comment]
Same error for me. Windows 11.  Current version of zotify as of today.
