### ISSUE TITLE
BadCredentials

### ISSUE THREAD

**Issue by 11plustwo** [zotify-dev/zotify#181]
I'm getting "BadCredentials" error when I try to use Zotify.

FYI, there is an existing ticket for this issue but it is closed and I'm unsure if the devs get notified about closed tickets. The existing ticket is https://github.com/zotify-dev/zotify/issues/167

I tried on mac and Windows.

macOS Ventura 13.6.9:

asdf@asdf-iMac ~ % zotify "https://open.spotify.com/playlist/12345" --download-lyrics=false --download-format=mp3 --download-quality=high
Username: XXXXXXXXXX@gmail.com
Password: ***************
Traceback (most recent call last):
  File "/Users/jeremy/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "/Users/jeremy/.local/pipx/venvs/zotify/lib/python3.9/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

Windows 10 Pro 10.0.19045 Build 19045:

C:\Users\asdf>zotify "https://open.spotify.com/playlist/12345" --download-lyrics=false --download-format=mp3 --download-quality=high
Username: XXXXXXXXXX@gmail.com
Password: *****************
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Scripts\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "C:\Users\asdf\AppData\Local\Programs\Python\Python312\Lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

**Comment by Thorneyyyy** [comment]
Having the same error on Debian 13.2.0

**Comment by rkmfl** [comment]
Same error despite immediately authenticating using the same credentials via the Spotify website.

Also accessing natively from a static IP in the U.S. where I've always used the service from.

No reason for some of the known issues; this is a new issue with Spotify/Zotify

Error:
**librespot.core.Session.SpotifyAuthenticationException: BadCredentials**

**Comment by Glaedr304** [comment]
https://github.com/librespot-org/librespot/issues/1308#issuecomment-2276196094

I suspect this is because spotify changed how users authenticate.

**Comment by akcharlie24** [comment]
> [librespot-org/librespot#1308 (comment)](https://github.com/librespot-org/librespot/issues/1308#issuecomment-2276196094)
> 
> I suspect this is because spotify changed how users authenticate.

what is the possible fix to this ?

**Comment by Glaedr304** [comment]
I am going to wait until the dev pushes an update, but if you are asking me how I think that should be implemented, I unfortunately have no idea.

**Comment by TheLastZombie** [comment]
Duplicate of #174; see [this comment](https://github.com/zotify-dev/zotify/issues/174#issuecomment-2295436663) for a workaround.

**Comment by MarvAmBass** [comment]
how to authenticate using the new oauth way:

install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token

run branch using:
 
```
cargo run --no-default-features -- --cache . --token ""
```

you'll need to open a link and let it redirect to the local librespot webservice.

if everything went well you end up with a `credentials.json` in the directory, which looks like this:

```
{
  "username": "QWERQWERQWERQWER",
  "auth_type": 1,
  "auth_data": "ASDFASDFASDF"
}
```

change it to look like the follwing:

```
{
  "username": "QWERQWERQWERQWER",
  "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
  "credentials": "ASDFASDFASDF"
}
```

and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`

**Comment by elidoz** [comment]
I have a problem with this, when I run the command

```cargo run --no-default-features -- --cache . --token ""```

I get a bunch of warnings, and after that the  credentials.json file is not created, it doesn't open any link on my internet browser, and I get this output

```
Error parsing command line options: Unrecognized option: 'token'

librespot 0.4.2 9d96efa (Built on 2024-09-08, Build ID: Bl43N9iw, Profile: debug)

An open source client library for Spotify, with support for Spotify Connect

https://github.com/librespot-org/librespot
```

I'm not sure I understand the part about the local librespot service, is it something more I have to set up?

**Comment by caoilainnl** [comment]
> how to authenticate using the new oauth way:
> 
> install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token
> 
> run branch using:
> 
> ```
> cargo run --no-default-features -- --cache . --token ""
> ```
> 
> you'll need to open a link and let it redirect to the local librespot webservice.
> 
> if everything went well you end up with a `credentials.json` in the directory, which looks like this:
> 
> ```
> {
>   "username": "QWERQWERQWERQWER",
>   "auth_type": 1,
>   "auth_data": "ASDFASDFASDF"
> }
> ```
> 
> change it to look like the follwing:
> 
> ```
> {
>   "username": "QWERQWERQWERQWER",
>   "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
>   "credentials": "ASDFASDFASDF"
> }
> ```
> 
> and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`

# Update

Some things have changed, this method works on Mac (Silicon chip) (It might work for any OS actually)

```zsh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo new project-name --bin
cd project-name
cargo build --release
git clone https://github.com/librespot-org/librespot
cd librespot
cargo run --no-default-features -- --cache . --enable-oauth
# Follow the login link printed to the terminal and login in your web browser
# ^C
cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
```

Place these credentials inside `~/Library/Application Support/Zotify/credentials.json`

**Comment by matthewye98** [comment]
> 

Hi, thanks for the detailed write up. Unfortunately, I'm still getting the same BadCredentials error even with a "fixed' credentials.json file. Is it normal to have Zotify ask for username and password even with the credentials.json file in place?

**Comment by DinkFloyp** [comment]
> > 
> 
> Hi, thanks for the detailed write up. Unfortunately, I'm still getting the same BadCredentials error even with a "fixed' credentials.json file. Is it normal to have Zotify ask for username and password even with the credentials.json file in place?

Maybe your command line calling zotify still makes use of parameters "--username" and "--paswword"  ... ?
If such is the case==> with confing.json properly setup you then want to REMOVE these 2 parameters from command line.

Also, maybe try to use parameter "--credentials-location" to explicitly give it the path to the json file you generated.

Below, a digest of zotify command line options.


----
usage: zotify [-h] [-ns] [--config-location CONFIG_LOCATION] [--username USERNAME] [--password PASSWORD] [-l] [-f]
              [-p] [-s [SEARCH]] [-d DOWNLOAD] [--save-credentials SAVE_CREDENTIALS]
              [--credentials-location CREDENTIALS_LOCATION] [--output OUTPUT] [--song-archive SONG_ARCHIVE]
              [--root-path ROOT_PATH] [--root-podcast-path ROOT_PODCAST_PATH] [--split-album-discs SPLIT_ALBUM_DISCS]
              [--download-lyrics DOWNLOAD_LYRICS] [--md-save-genres MD_SAVE_GENRES] [--md-allgenres MD_ALLGENRES]
              [--md-genredelimiter MD_GENREDELIMITER] [--download-format DOWNLOAD_FORMAT]
              [--download-quality DOWNLOAD_QUALITY] [--transcode-bitrate TRANSCODE_BITRATE]
              [--skip-existing SKIP_EXISTING] [--skip-previously-downloaded SKIP_PREVIOUSLY_DOWNLOADED]
              [--retry-attempts RETRY_ATTEMPTS] [--bulk-wait-time BULK_WAIT_TIME]
              [--override-auto-wait OVERRIDE_AUTO_WAIT] [--chunk-size CHUNK_SIZE]
              [--download-real-time DOWNLOAD_REAL_TIME] [--language LANGUAGE] [--print-splash PRINT_SPLASH]
              [--print-skips PRINT_SKIPS] [--print-download-progress PRINT_DOWNLOAD_PROGRESS]
              [--print-errors PRINT_ERRORS] [--print-downloads PRINT_DOWNLOADS] [--print-api-errors PRINT_API_ERRORS]
              [--print-progress-info PRINT_PROGRESS_INFO] [--print-warnings PRINT_WARNINGS]
              [--temp-download-dir TEMP_DOWNLOAD_DIR]
              [urls ...]

**Comment by satonotdead** [comment]
> ```shell
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> cargo new project-name --bin
> cd project-name
> cargo build --release
> git clone https://github.com/librespot-org/librespot
> cd librespot
> cargo run --no-default-features -- --cache . --enable-oauth
> # Follow the login link printed to the terminal and login in your web browser
> # ^C
> cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
> ```

Wow, thanks for this guide. I can confirm this working on MacOS :)

**Comment by Minetrio1256** [comment]
> > how to authenticate using the new oauth way:
> > install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token
> > run branch using:
> > ```
> > cargo run --no-default-features -- --cache . --token ""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you'll need to open a link and let it redirect to the local librespot webservice.
> > if everything went well you end up with a `credentials.json` in the directory, which looks like this:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "auth_type": 1,
> >   "auth_data": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change it to look like the follwing:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
> >   "credentials": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`
> 
> # Update
> Some things have changed, this method works on Mac (Silicon chip) (It might work for any OS actually)
> 
> ```shell
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> cargo new project-name --bin
> cd project-name
> cargo build --release
> git clone https://github.com/librespot-org/librespot
> cd librespot
> cargo run --no-default-features -- --cache . --enable-oauth
> # Follow the login link printed to the terminal and login in your web browser
> # ^C
> cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
> ```
> 
> Place these credentials inside `~/Library/Application Support/Zotify/credentials.json`

that's cool I have the credentials.json file but what argument do I use because it just gives me the username and password prompt.
Here is the command that I use: "zotify https://open.spotify.com/playlisturl --credentials-location "~/Library/Application Support/Zotify/credentials.json"
"

**Comment by satonotdead** [comment]
Did you tried without `credentials.json`? I'm not close to the laptop but it probably do the trick.

Or just using the default folder with `zotify` as is.

**Comment by Minetrio1256** [comment]
> Did you tried without `credentials.json`? I'm not close to the laptop but it probably do the trick.
> 
> Or just using the default folder with `zotify` as is.

yes I did and it just ask me for my username and password and you need oauth as of right now

**Comment by satonotdead** [comment]
I kindly suggest you to put the credentials into default folder of your system and skipp to add the variable. It should work.

**Comment by Minetrio1256** [comment]
> I kindly suggest you to put the credentials into default folder of your system and skipp to add the variable. It should work.

if you mean putting the credentials in application support/zotify/,
yes I did and it still ask me for may username and password.

**Comment by raymart-evangelista** [comment]
> > I kindly suggest you to put the credentials into default folder of your system and skipp to add the variable. It should work.
> 
> if you mean putting the credentials in application support/zotify/, yes I did and it still ask me for may username and password.

Hey @Minetrio1256,
I believe @satonotdead means to put the credentials in the root directory where you are located when you use the `cd` command. I was able to get it working by doing `cp credentials.json ~/` when inside the librespot directory. Hope this helps!

**Comment by Minetrio1256** [comment]
> > > I kindly suggest you to put the credentials into default folder of your system and skipp to add the variable. It should work.
> > 
> > 
> > if you mean putting the credentials in application support/zotify/, yes I did and it still ask me for may username and password.
> 
> Hey @Minetrio1256, I believe @satonotdead means to put the credentials in the root directory where you are located when you use the `cd` command. I was able to get it working by doing `cp credentials.json ~/` when inside the librespot directory. Hope this helps!

The credentials.json is in the root directory and in ~/Library/Application Support/Zotify/credentials.json

**Comment by fleetvonr** [comment]
Hi @Minetrio1256 I had the same problem until I tried with:
`zotify --config-location ~/Library/Application\ Support/Zotify/config.json --credentials-location ~/Library/Application\ Support/Zotify/credentials.json https://open.spotify.com/playlist/xyz`
With both parameters config-location and credentials-location it worked.

**Comment by fabrizionunezt** [comment]
> > how to authenticate using the new oauth way:
> > install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token
> > run branch using:
> > ```
> > cargo run --no-default-features -- --cache . --token ""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you'll need to open a link and let it redirect to the local librespot webservice.
> > if everything went well you end up with a `credentials.json` in the directory, which looks like this:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "auth_type": 1,
> >   "auth_data": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change it to look like the follwing:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
> >   "credentials": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`
> 
> # Update
> Some things have changed, this method works on Mac (Silicon chip) (It might work for any OS actually)
> 
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> cargo new project-name --bin
> cd project-name
> cargo build --release
> git clone https://github.com/librespot-org/librespot
> cd librespot
> cargo run --no-default-features -- --cache . --enable-oauth
> # Follow the login link printed to the terminal and login in your web browser
> # ^C
> cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
> Place these credentials inside `~/Library/Application Support/Zotify/credentials.json`


Tried this on Windows and got it working by following these steps:

Cloned the librespot repo and ran:

`cargo run --no-default-features -- --cache . --enable-oauth
`
Note 1: I had to install CMake manually from [cmake.org](https://cmake.org/download/) because cargo was failing with this error:
`Missing dependency: cmake
thread 'main' panicked at C:\Users\pc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\aws-lc-sys-0.22.0\builder\main.rs:320:40:
called Result::unwrap() on an Err value: "Required build`

Logged in using the link printed in the terminal, then stopped it with Ctrl + C.
Librespot generates a credentials.json in its root, but you need to modify it:
Change the order of the fields
Rename some keys so it looks like this:
`{
    "username": "your_username", 
    "credentials": "auth_data", 
    "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS"
}`
Note 2: I had to change the order of the fields in credentials.json, because otherwise, Zotify ignored it and kept asking for my username and password. Ideally, it should detect the configuration automatically.

Moved the modified credentials.json to
`C:\Users\YOUR_USER\AppData\Roaming\Zotify\credentials.json
`
Also checked Zotify's config in that folder in case any adjustments were needed.
Here’s my current configuration:
`{
    "SAVE_CREDENTIALS": "False",
    "CREDENTIALS_LOCATION": "C:\\Users\\pc\\AppData\\Roaming\\Zotify\\credentials.json",
    "OUTPUT": "",
    "SONG_ARCHIVE": "",
    "ROOT_PATH": "C:\\Users\\pc\\Documents\\Music", 
    "ROOT_PODCAST_PATH": "",
    "SPLIT_ALBUM_DISCS": "False",
    "DOWNLOAD_LYRICS": "False",
    "MD_SAVE_GENRES": "False",
    "MD_ALLGENRES": "False",
    "MD_GENREDELIMITER": ",",
    "DOWNLOAD_FORMAT": "mp3",
    "DOWNLOAD_QUALITY": "very_high",
    "TRANSCODE_BITRATE": "auto",
    "SKIP_EXISTING": "True",
    "SKIP_PREVIOUSLY_DOWNLOADED": "True",
    "RETRY_ATTEMPTS": "1",
    "BULK_WAIT_TIME": "1",
    "OVERRIDE_AUTO_WAIT": "False",
    "CHUNK_SIZE": "20000",
    "DOWNLOAD_REAL_TIME": "False",
    "LANGUAGE": "en",
    "PRINT_SPLASH": "False",
    "PRINT_SKIPS": "True",
    "PRINT_DOWNLOAD_PROGRESS": "True",
    "PRINT_ERRORS": "True",
    "PRINT_DOWNLOADS": "False",
    "PRINT_API_ERRORS": "True",
    "PRINT_PROGRESS_INFO": "True",
    "PRINT_WARNINGS": "True",
    "TEMP_DOWNLOAD_DIR": "C:\\Users\\pc\\AppData\\Roaming\\Zotify"
}
`

Hope this helps someone!

**Comment by bangity** [comment]
> > > how to authenticate using the new oauth way:
> > > install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token
> > > run branch using:
> > > ```
> > > cargo run --no-default-features -- --cache . --token ""
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > you'll need to open a link and let it redirect to the local librespot webservice.
> > > if everything went well you end up with a `credentials.json` in the directory, which looks like this:
> > > ```
> > > {
> > >   "username": "QWERQWERQWERQWER",
> > >   "auth_type": 1,
> > >   "auth_data": "ASDFASDFASDF"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > change it to look like the follwing:
> > > ```
> > > {
> > >   "username": "QWERQWERQWERQWER",
> > >   "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
> > >   "credentials": "ASDFASDFASDF"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >   
> > > and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`
> > 
> > 
> > # Update
> > Some things have changed, this method works on Mac (Silicon chip) (It might work for any OS actually)
> > curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> > cargo new project-name --bin
> > cd project-name
> > cargo build --release
> > git clone https://github.com/librespot-org/librespot
> > cd librespot
> > cargo run --no-default-features -- --cache . --enable-oauth
> > # Follow the login link printed to the terminal and login in your web browser
> > # ^C
> > cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
> > Place these credentials inside `~/Library/Application Support/Zotify/credentials.json`
> 
> Tried this on Windows and got it working by following these steps:
> 
> Cloned the librespot repo and ran:
> 
> `cargo run --no-default-features -- --cache . --enable-oauth ` Note 1: I had to install CMake manually from [cmake.org](https://cmake.org/download/) because cargo was failing with this error: `Missing dependency: cmake thread 'main' panicked at C:\Users\pc\.cargo\registry\src\index.crates.io-6f17d22bba15001f\aws-lc-sys-0.22.0\builder\main.rs:320:40: called Result::unwrap() on an Err value: "Required build`
> 
> Logged in using the link printed in the terminal, then stopped it with Ctrl + C. Librespot generates a credentials.json in its root, but you need to modify it: Change the order of the fields Rename some keys so it looks like this: `{ "username": "your_username", "credentials": "auth_data", "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS" }` Note 2: I had to change the order of the fields in credentials.json, because otherwise, Zotify ignored it and kept asking for my username and password. Ideally, it should detect the configuration automatically.
> 
> Moved the modified credentials.json to `C:\Users\YOUR_USER\AppData\Roaming\Zotify\credentials.json ` Also checked Zotify's config in that folder in case any adjustments were needed. Here’s my current configuration: `{ "SAVE_CREDENTIALS": "False", "CREDENTIALS_LOCATION": "C:\\Users\\pc\\AppData\\Roaming\\Zotify\\credentials.json", "OUTPUT": "", "SONG_ARCHIVE": "", "ROOT_PATH": "C:\\Users\\pc\\Documents\\Music", "ROOT_PODCAST_PATH": "", "SPLIT_ALBUM_DISCS": "False", "DOWNLOAD_LYRICS": "False", "MD_SAVE_GENRES": "False", "MD_ALLGENRES": "False", "MD_GENREDELIMITER": ",", "DOWNLOAD_FORMAT": "mp3", "DOWNLOAD_QUALITY": "very_high", "TRANSCODE_BITRATE": "auto", "SKIP_EXISTING": "True", "SKIP_PREVIOUSLY_DOWNLOADED": "True", "RETRY_ATTEMPTS": "1", "BULK_WAIT_TIME": "1", "OVERRIDE_AUTO_WAIT": "False", "CHUNK_SIZE": "20000", "DOWNLOAD_REAL_TIME": "False", "LANGUAGE": "en", "PRINT_SPLASH": "False", "PRINT_SKIPS": "True", "PRINT_DOWNLOAD_PROGRESS": "True", "PRINT_ERRORS": "True", "PRINT_DOWNLOADS": "False", "PRINT_API_ERRORS": "True", "PRINT_PROGRESS_INFO": "True", "PRINT_WARNINGS": "True", "TEMP_DOWNLOAD_DIR": "C:\\Users\\pc\\AppData\\Roaming\\Zotify" } `
> 
> Hope this helps someone!

All of that was a pain in the butt. I use spotDL so far but it kept giving me errors or in queue after half of the list so I am trying Zotify. It's much more complicated to setup but it seems to be working!!

**Comment by shanaythakkar** [comment]
Hey all, tried the above to clone the librespot repo, generate the creds and move them to the zotify folder in AppData\Roaming. So first issue I noticed is that there was no Zotify folder in Roaming so I went ahead and created one and put both the config and creds files there. When I try to run, I'm getting the following errors:

![Image](https://github.com/user-attachments/assets/a3009ab4-d153-470b-857b-0852e222f8ba)

Any advice?

**Comment by hkirsman** [comment]
This has indeed painful, but only 1-2 hours of trying with above 🙂 

Somet things for mac I needed and remember:

1.
Instead of _cargo run --no-default-features -- --cache . --enable-oauth_ because at least I got errors:
run:
`cargo run --no-default-features --features "native-tls" --release -- --cache . --enable-oauth`

2. Put your config and credentials in:
~/Library/Application\ Support/Zotify/

in ~/Library/Application\ Support/Zotify/config.json set the credentials.json with full path. SAVE_CREDENTIALS needs to be true Mine is:
```
{
    "SAVE_CREDENTIALS": "True",
    "CREDENTIALS_LOCATION": "/Users/hannes/Library/Application Support/Zotify/credentials.json",
     ...
```

set up ~/Library/Application\ Support/Zotify/credentials.json: - you get those after cargo run and need to copy the file from your current location to ~/Library/Application\ Support/Zotify/credentials.json and then change the keys according to this.

```
{
    "username": "",
    "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
    "credentials": ""
}
```

And finally also:
`brew install ffmpeg`

Music by default is saved to:
~/Music/Zotify\ Music


And it might be that after all the trying your session has expired, so create fresh credentials.json

**Comment by hkirsman** [comment]
I added the script here that generates the credentials.json https://github.com/hkirsman/refresh_spotify_token.sh/tree/main

**Comment by DreaTheEmpress-x3** [comment]
> > how to authenticate using the new oauth way:
> > install git, rust and cargo, download the following branch of librespot https://github.com/kingosticks/librespot/tree/credentials_with_access_token
> > run branch using:
> > ```
> > cargo run --no-default-features -- --cache . --token ""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you'll need to open a link and let it redirect to the local librespot webservice.
> > if everything went well you end up with a `credentials.json` in the directory, which looks like this:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "auth_type": 1,
> >   "auth_data": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change it to look like the follwing:
> > ```
> > {
> >   "username": "QWERQWERQWERQWER",
> >   "type": "AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",
> >   "credentials": "ASDFASDFASDF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you're done - don't forget to refrence the `credentials.json` in you `zotify/config.json`
> 
> # Update
> Some things have changed, this method works on Mac (Silicon chip) (It might work for any OS actually)
> 
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> cargo new project-name --bin
> cd project-name
> cargo build --release
> git clone https://github.com/librespot-org/librespot
> cd librespot
> cargo run --no-default-features -- --cache . --enable-oauth
> # Follow the login link printed to the terminal and login in your web browser
> # ^C
> cat credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'
> Place these credentials inside `~/Library/Application Support/Zotify/credentials.json`

so i have an issue here, everytime i run the comman under cd librespot it has a error calling dlltool issue and idk why this is
