### ISSUE TITLE
Application closes/crashes when trying to login

### ISSUE THREAD

**Issue by bdifh** [zotify-dev/zotify#185]
I am new to this. so I try to login, but immediately after I press enter after filling in the password the application shuts down/closes/crashes.

Am I doing something wrong?
I tried to re-install the application following the 'installation' thing for Wiindows.

**Comment by Tromick** [comment]
Same here.

**Comment by ridolagunju** [comment]
same here
```
Traceback (most recent call last):

  File "/home/rid/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "/home/rid/.local/share/pipx/venvs/zotify/lib/python3.12/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials
```

**Comment by bdifh** [comment]
Found this in the discord server. Solved it for us (see screenshot) 
 
![Screenshot_20240906-144535](https://github.com/user-attachments/assets/dfc4faa8-36e5-4a42-bd52-89dd96505a8e)

**Comment by ridolagunju** [comment]
oof what a roundabout fix
