### ISSUE TITLE
py error, help pls

### ISSUE THREAD

**Issue by Draxxx** [zotify-dev/zotify#192]
Sorry nub here. 
Fresh re-install of Zotify. 
Python 3.12.5, ffmpeg 7.0.2
Generated 'credentials.json' successfully, and ammended, updated config.json, but getting the following errors';

PS C:\Users\test> zotify -l
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\test\.local\bin\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\test\pipx\venvs\zotify\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\test\pipx\venvs\zotify\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
  File "C:\Users\test\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 20, in __init__
    Zotify.CONFIG.load(args)
  File "C:\Users\test\pipx\venvs\zotify\Lib\site-packages\zotify\config.py", line 106, in load
    jsonvalues = json.load(config_file)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\scoop\apps\python\current\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\test\scoop\apps\python\current\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\scoop\apps\python\current\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\scoop\apps\python\current\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 32 (char 65)

Anyone able to tell me what's causing the error?
Would greatly appreciate any help. 
Thanks in advance!

**Comment by korybourek** [comment]
I had the same issue. I was able to fix it by installing by pip not pipx:

run:
pip install https://get.zotify.xyz

I this doesn't work, it will atleast give you a better log of where the errors are.
