### ISSUE TITLE
Cannot log in with correct name and password

### ISSUE THREAD

**Issue by nemisnemo** [zotify-dev/zotify#202]
Password: ************
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Scripts\zotify.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trøsykkel med motor\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException:

What am i doing wrong? i cannot code btw, barely know what im doing

**Comment by caoilainnl** [comment]
I think your credentials file needs the variable names changed, try

`cat path/to/credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS",/' | sed 's/auth_data/credentials/'`

**Comment by nemisnemo** [comment]
sed : The term 'sed' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:32
+ cat path/to/credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTI ...
+                                ~~~
    + CategoryInfo          : ObjectNotFound: (sed:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by caoilainnl** [comment]
> sed : The term 'sed' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:32
> 
>     * cat path/to/credentials.json | sed 's/"auth_type":1,/"type":"AUTHENTI ...
> 
>     * ```
>                                  ~~~
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       
>       * CategoryInfo          : ObjectNotFound: (sed:String) [], CommandNotFoundException
>       * FullyQualifiedErrorId : CommandNotFoundException

just replace `"auth_type":1,` with `"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS"` and `auth_data` with `credentials` in your credentials.json

**Comment by betrieb** [comment]
I just tried to use this for the first time and had exactly the same issue

**Comment by marcfusch** [comment]
same issue here, cannot find the credential file since it has not been created by zotify :/

**Comment by Nirmal193** [comment]
guys please do not install this it will not work getting the badcredential after multiple tries have also added the creds in the code but no progress do not weste your time in this
