### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by Droidman007** [zotify-dev/zotify#205]
Username: 31rbczat4ilnld464i3s2rzcpvlu
Password: ***********
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/zotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials
~ $

**Comment by detafuro** [comment]
Download the dev branch that one works.
