### ISSUE TITLE
Login error - First time using zotify

### ISSUE THREAD

**Issue by hrishi1610** [zotify-dev/zotify#207]
I checked the credntials, they are right. What am i doing wrong? I do not have spotify premium that is why i download songs offline. I do not code. SO I REQUEST SOMEONE TO HELP ME OUT!

Getting this error below the correct username and password -

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\hrish\.local\bin\zotify.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hrish\pipx\venvs\zotify\Lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

**Comment by detafuro** [comment]
Download the dev branch that one works.

**Comment by unclesimey** [comment]
> Download the dev branch that one works.

do you have a link?

**Comment by seangibbz** [comment]
> > Download the dev branch that one works.
> 
> do you have a link?

https://github.com/zotify-dev/zotify/tree/v1.0-dev

Using git:
```git
git clone -b v1.0-dev https://github.com/zotify-dev/zotify.git
```

**Comment by xelrix** [comment]
I couldn't get that to work. Do I need to install the latest librespot?

Nevermind. Solved using this solution:
https://github.com/zotify-dev/zotify/issues/174#issuecomment-2481266378

**Comment by nehasjains** [comment]
I am using Mac OS X, How to fix this error ? Kindly guide

**Comment by adabru** [comment]
```
pip install https://github.com/zotify-dev/zotify/archive/refs/heads/v1.0-dev.zip
```

The dev branch replaces the password with an oauth token. No complex procedure, you just have to click a link the first using it.

**Comment by nehasjains** [comment]
> ```
> pip install https://github.com/zotify-dev/zotify/archive/refs/heads/v1.0-dev.zip
> ```
> 
> The dev branch replaces the password with an oauth token. No complex procedure, you just have to click a link the first using it.

thank you so much it worked

**Comment by babylegzz** [comment]
> ```
> pip install https://github.com/zotify-dev/zotify/archive/refs/heads/v1.0-dev.zip
> ```
> 
> The dev branch replaces the password with an oauth token. No complex procedure, you just have to click a link the first using it.

when you say you have to click a link the first time using it, what link are you talking about?  i don't have any links or anything.  it just keeps erroring out.

edit: disregard.  for anyone else trying dev branch after anything else, you have to delete your OG config.json file for the link to populate when using dev

**Comment by Apothestes** [comment]
> > ```
> > pip install https://github.com/zotify-dev/zotify/archive/refs/heads/v1.0-dev.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The dev branch replaces the password with an oauth token. No complex procedure, you just have to click a link the first using it.
> 
> when you say you have to click a link the first time using it, what link are you talking about? i don't have any links or anything. it just keeps erroring out.
> 
> edit: disregard. for anyone else trying dev branch after anything else, you have to delete your OG config.json file for the link to populate when using dev

How do you do delete the og file? I'm pretty unfamiliar with this sort of thing and am learning on the fly lol.
