### ISSUE TITLE
[Bug] Installing zotify using NIX throws protobuf incompatibility error

### ISSUE THREAD

**Issue by putnap** [zotify-dev/zotify#212]
Hello,

I am using nix to manage my packages in a declarative way on my mac machine. Since I found zotify on nix packages, I thought I could just install it, however, I am facing an issue.

I am not great with python and how to manage it's dependencies and I realise that my problem is **niche**, but maybe someone can help me.

When trying to run simple `nix-shell -p zotify` command to try out if the tool will work, I get this error:

```
error: builder for '/nix/store/lzkb8nyh4a8qcnpa62v07na56dxx6i5k-python3.12-librespot-0.0.9.drv' failed with exit code 1;
       last 25 log lines:
       > Traceback (most recent call last):
       >   File "<string>", line 1, in <module>
       >   File "<string>", line 1, in <lambda>
       >   File "/nix/store/ybnf7k6i9p244bbhsbxizqk65z58cwyr-python3-3.12.6/lib/python3.12/importlib/__init__.py", line 90, in import_module
       >     return _bootstrap._gcd_import(name[level:], package, level)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
       >   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
       >   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
       >   File "/nix/store/5m013giqzng119a8cad92dcw880pr11i-python3.12-librespot-0.0.9/lib/python3.12/site-packages/librespot/__init__.py", line 3, in <module>
       >     from librespot.proto.Keyexchange_pb2 import BuildInfo, Platform, Product, ProductFlags
       >   File "/nix/store/5m013giqzng119a8cad92dcw880pr11i-python3.12-librespot-0.0.9/lib/python3.12/site-packages/librespot/proto/Keyexchange_pb2.py", line 31, in <module>
       >     _descriptor.EnumValueDescriptor(
       >   File "/nix/store/a7qv2pc2lkpfhl28pq4rn0nk49dkm081-python3.12-protobuf-5.28.2/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 920, in __new__
       >     _message.Message._CheckCalledFromGeneratedFile()
       > TypeError: Descriptors cannot be created directly.
       > If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
       > If you cannot immediately regenerate your protos, some other possible workarounds are:
       >  1. Downgrade the protobuf package to 3.20.x or lower.
       >  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
       >
       > More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
       For full logs, run 'nix log /nix/store/lzkb8nyh4a8qcnpa62v07na56dxx6i5k-python3.12-librespot-0.0.9.drv'.
error: 1 dependencies of derivation '/nix/store/96132hp53ihb6k9lqxinj3zj7j64y9rx-zotify-0.6.13.drv' failed to build
```

P.S. In my opinion, if package is in package manager, I assume it should work out of the box. So maybe something can be done on zotify side or package pulled from [repo](https://search.nixos.org/packages?channel=unstable&show=zotify&from=0&size=50&sort=relevance&type=packages&query=zotify) all together.

**Comment by exuvo** [comment]
Same problem on Arch linux, PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python seems to work but cant download anything but i think that is a different issue.
