### ISSUE TITLE
bad credentials

### ISSUE THREAD

**Issue by owoyep1** [zotify-dev/zotify#217]
Username: k9jwhe66alqwi2jru8bs0eyyf
Password: **********
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\potat\scoop\apps\python\current\Scripts\zotify.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potat\scoop\apps\python\current\Lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

i have absolutely no clue what im doing, please help

**Comment by andrefromsbg** [comment]
same here

**Comment by satonotdead** [comment]
Possible solution on #207
