### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by hyugatakagi** [zotify-dev/zotify#230]
I am also having this error on MacOS. Please kindly guide me if I am doing something wrong.

Traceback (most recent call last):
  File "/Users/hyuga/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/hyuga/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials

**Comment by SlowlyTz** [comment]
what did u do to fix this error?
