### ISSUE TITLE
BadCredentials on mac

### ISSUE THREAD

**Issue by TheGrumpyDino67** [zotify-dev/zotify#232]
I am a mac user (and a complete idiot when it comes to anything related to code), and while attempting to find solutions for this message (Traceback (most recent call last):
  File "/Users/suriadijohansjah/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/suriadijohansjah/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials) while using Zotify, I discovered that there are no solutions I can find for mac. is there a solution for this problem? Thanks

**Comment by DmitryZemlyuk** [comment]
Hi :)
Try to install from dev branch
"python -m pip install git+https://zotify.xyz/zotify/zotify.git@v1.0-dev"

**Comment by Happyfeet748** [comment]
ive attmped that also uninstalling and re-installing multiple times i get the same issue he does on mac.

` File "/Users/xx/.local/bin/zotify", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/app.py", line 21, in client
    Zotify(args)
    ~~~~~~^^^^^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 21, in __init__
    Zotify.login(args)
    ~~~~~~~~~~~~^^^^^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/zotify/zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/.local/pipx/venvs/zotify/lib/python3.13/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials`

**Comment by jacobslusser** [comment]
> Hi :) Try to install from dev branch "python -m pip install git+https://zotify.xyz/zotify/zotify.git@v1.0-dev"

This branch is 11 commits ahead, and **101 commits behind**. The CLI has a lot of incompatibilities and doesn't seem to support things like `--download-real-time=True`

EDIT: To clarify, just letting others know that this branch is like a different app.

**Comment by wilhelm115** [comment]
Hi @jacobslusser,
I'm new here. 
What means "commits behind" ? The version number is 1.0 shouldn't it be "before" instead of behind 'cause its a newer version ? (if my english is good enough and I'm understanding this correctly...)

**Comment by wilhelm115** [comment]
Ok I have something new:

I used the [v1.0-dev](https://zotify.xyz/zotify/zotify.git@v1.0-dev) version
and installed it on my Android!
and... is works 🎉

1. Install Termux from PlayStore 
2. Open your standard web browser and log into a burner account (needs to be 24h old and stream a few songs, other wise the api refused the connection (in my case...))
4. Install this packages by running those commands 'cause it won't work otherwise: 
 ```
pkg update && pkg upgrade
pkg install python git 
pkg install libjpeg-turbo libjpeg-turbo zlib clang
```

5. then install zotify:
```
python -m pip install git+https://zotify.xyz/zotify/zotify.git@v1.0-dev
```
6. search for a song with `zotify -s <song name>`
7. Type your username in: `Username: <username>` (go to https://www.spotify.com/de/account/profile/ and copy/paste)
8. A Message should pop up: `Click on the following link to login:
https://accounts.spotify.com/authorize.............`

Copy this link into the same browser where you previously logged in. You should see: `Authorization successful. You can close this window.`
9. If you switch back to termux then it has already listed the songs you are looking for and you can use zotify as normal 🎉
10. To move the downloaded files inside the Files app you need to use the `termux-setup-storage` command in Termux (https://wiki.termux.com/wiki/Termux-setup-storage)

**Comment by jacobslusser** [comment]
@wilhelm115 Glad you got it working. I was also able to get the `1.0-dev` branch working after I changed my command line params to the new format. 

My statement about commits ahead and behind comes from GitHub branch compare. I agree it is misleading when it says the `1.0-dev` branch is 101 commits behind, even though it is "newer" in terms of development. As I understand Git, there are several reasons it could be reported like this, all of which could be summed up as "these branches have not been merging changes between them to stay consistent".

![Image](https://github.com/user-attachments/assets/3605e264-375e-4d74-b09a-d05dfebb7b8b)

**Comment by jaynetics** [comment]
the dev version can also be installed with the normal instructions and pipx:

```
pipx install git+https://zotify.xyz/zotify/zotify.git@v1.0-dev --force
```

**Comment by satonotdead** [comment]
> > Hi :) Try to install from dev branch "python -m pip install git+https://zotify.xyz/zotify/zotify.git@v1.0-dev"
> 
> This branch is 11 commits ahead, and **101 commits behind**. The CLI has a lot of incompatibilities and doesn't seem to support things like `--download-real-time=True`
> 
> EDIT: To clarify, just letting others know that this branch is like a different app.

May I know what's the current working version? Are you using Zotify?

101 commits are a lot to take into consideration.
