### ISSUE TITLE
Failed fetching audio key! (traceback calls)

### ISSUE THREAD

**Issue by 7eventy7** [zotify-dev/zotify#234]
I had this application working just last week but when attempting to use it today I'm getting nothing but errors:

```       [∙∙∙] Preparing download... Audio key error, code: 1
        [∙∙∙] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Catch Fire (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 5ijJ0xC7RlUUB8RCsg2z1C
album_num: 01
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: adfdf206afc7462c85449aaaf5eb8e60, fileId: 4157716f83a2aa288838646c266492ea1783555e

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: adfdf206afc7462c85449aaaf5eb8e60, fileId: 4157716f83a2aa288838646c266492ea1783555e


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Harlem Nights (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 7f5FgKkeLMeDEwsbvmVsrn
album_num: 02
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: edfee355593d43cbab2e4b8d7e4d6e89, fileId: 5f5961a2250b3e3420c866511ced8a163bd93599

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: edfee355593d43cbab2e4b8d7e4d6e89, fileId: 5f5961a2250b3e3420c866511ced8a163bd93599


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Versatile 4 (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 1fjJ70TjK6fIf6gswcmRAD
album_num: 03
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: 28f98721fa42421b9c7ba2f0c01bc1c3, fileId: d3dea6fce0fcfe081820ca1e5f58b6f377f0ea84

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 28f98721fa42421b9c7ba2f0c01bc1c3, fileId: d3dea6fce0fcfe081820ca1e5f58b6f377f0ea84


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Drive The Boat (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 2EeaJokLoMX2e3ZAGraQaY
album_num: 04
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: 5708676e52de46bf99baefb001ff8b18, fileId: 41237628d8456a1efd4956a8e21b9b9577dfb79e

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 5708676e52de46bf99baefb001ff8b18, fileId: 41237628d8456a1efd4956a8e21b9b9577dfb79e


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Never Exaggerate (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 3vryrfxXg67KaduTCKe3AD
album_num: 05
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: 733c09f80c5541078e1f170a50d20d5b, fileId: d14fe527b3d1785e31439053345227f31dafdf72

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 733c09f80c5541078e1f170a50d20d5b, fileId: d14fe527b3d1785e31439053345227f31dafdf72


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Never See Me (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 30CIKWOJ564yIpVXefrud9
album_num: 06
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: 62e6cba706694c5b83d50d43a7ee103f, fileId: 023c5763e82957bacc46415815b7f72f6add9adb

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 62e6cba706694c5b83d50d43a7ee103f, fileId: 023c5763e82957bacc46415815b7f72f6add9adb


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Ima Be Real (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 6waqKeC17KOoOXcFUlzeva
album_num: 07
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: d6304cf0146242d3ad72376b78cf4f3c, fileId: eef4f8e340b689ed6a2df27d7909d12400c3303b

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: d6304cf0146242d3ad72376b78cf4f3c, fileId: eef4f8e340b689ed6a2df27d7909d12400c3303b


        [∙●∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Kodak Black - Inside I Suffer (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 03GDgHkafw5N7zEzEwAnle
album_num: 08
artist: Kodak Black
album: Dieuson Octave
album_id: 5MMgxR8kqI7CFzQRvGiKHj


Failed fetching audio key! gid: 01f44a5b2d2e4e1f95da1355f4f15c20, fileId: 551b6ec844d7c527247744269d67d8aeb9fef6f0

Traceback (most recent call last):
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 228, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Garnet\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 01f44a5b2d2e4e1f95da1355f4f15c20, fileId: 551b6ec844d7c527247744269d67d8aeb9fef6f0


100%|█████████████████████████████████████████████████████████████████████████████| 8.00/8.00 [00:07<00:00, 1.00Song/s]```

**Comment by gk5521** [comment]
I think it is bug or network issue

**Comment by 7eventy7** [comment]
I've attempted to switch to the 1.0 dev branch but I am still receiving errors. Any help would be greatly appreciated.

``` | Fetching track... Audio key error, code: 1
 / Fetching track... Audio key error, code: 1

RuntimeError: Failed fetching audio key! gid: 5c9b917ac2d740458fe4dcfcf9ccf50c, fileId: a16852577b95a07100b20902ed697c74efac1d72```

**Comment by 7eventy7** [comment]
Well this is embarrassing, the issue was that I did not have Spotify premium enabled.

**Comment by bscag** [comment]
> Well this is embarrassing, the issue was that I did not have Spotify premium enabled.

i have the same error 
do i just buy premium for this account? was that it?

**Comment by edxeth** [comment]
@7eventy7 I'm having the same issue. Does Zotify require a premium Spotify subscription? It's not clear. I'm a free user, by the way.
@bscag did you maybe get a premium subscription to test Zotify?

**Comment by 7eventy7** [comment]
> [@7eventy7](https://github.com/7eventy7) I'm having the same issue. Does Zotify require a premium Spotify subscription? It's not clear. I'm a free user, by the way. [@bscag](https://github.com/bscag) did you maybe get a premium subscription to test Zotify?

Spotify premium was the issue for me, I subscribed for a month and downloaded all the music I needed

**Comment by Le0X8** [comment]
I'm a premium user myself, but I keep hitting the rate limit over and over again. It only downloads like 100 songs at a time, then you need to wait like 15 mins and try again.

I know this is very time intensive (my playlist has ~3k tracks), but besides [this fork](https://github.com/bgeorgakas/zotify), there isn't really a solution to this issue.

Edit: changed link to the fork

**Comment by edxeth** [comment]
@Le0X8 yes, the fork with a 30-second delay works like a charm for 160kbps audio quality as free users. However, I wasn't able to download the metadata cover-art but every other info such as artist, album, date, etc. was picked up. Did you maybe face the same issue?
By the way, I may also upgrade to premium for a month just to get the 320kbps audio quality, lmao!

**Comment by Le0X8** [comment]
No, the only issue I was facing was the cover art that was downloaded on the first downloaded and copied to every single track, so Mozart had weed on his cover art 💀

I simply just ran another script in parallel that automatically removes the cover.jpg every time it was created as there is no way to turn this feature off.

I also realized that with my shitty internet connection (I live in Germany) I get a connection reset every 2 hrs, so leaving the script running overnight makes no sense for me. Unfortunately, it would me more efficient for me to rerun the script everytime a key error occurs as using the timeout method.

That way, I can download like 80 songs in 2 mins, get some errors and rerun the thing after like 15 minutes. I think my liked songs won't be downloaded until Saturday as I will not download music all day lol, I still have a life.

Anyways, I'm wishing you good luck with your attempt! :)

**Comment by edxeth** [comment]
@Le0X8 don't do me like that bro I wasted 4 hours with DeepSeek-R1 671B and Grok 3 to write a working Python script that leverages Zotify's credentials and Spotify's API to grab cover-arts for each track from their metadata 💀

https://gist.github.com/edxeth/c06f46650e0091d3b2f9beb1dc7dd475

So, if I actually delete `cover.jpg' before the next track is downloaded then I may get all the cover-arts without running the above script for instance?

**Comment by Le0X8** [comment]
Yes. But here's my bash script:

```bash
while [ 1 ]
do
  rm cover.png
done
```

I actually created a Spotify scraper a few years ago in JS, but idk if it still works (so you don't need the API): [@Le0X8/spotifydb](https://github.com/Le0X8/spotifydb) (well this worked in 2022)

**Comment by Le0X8** [comment]
Yes. But here's my bash script:

```bash
while [ 1 ]
do
  rm cover.png
done
```

I actually created a Spotify scraper a few years ago in JS, but idk if it still works (so you don't need the API): [@Le0X8/spotifydb](https://github.com/Le0X8/spotifydb) (well this worked in 2022)

**Comment by edxeth** [comment]
@Le0X8 not sure if you're interested but here's how to fix the cover-art issue as demonstrated in my pull request: https://github.com/bgeorgakas/zotify/pull/8/commits/bdffb90d493b810ef305e7d6be73893621841bad

Link to my fork: https://github.com/edxeth/zotify

**Comment by Le0X8** [comment]
@edxeth Thanks, I'll check it out soon!
