### ISSUE TITLE
Error Message when Running Zotify

### ISSUE THREAD

**Issue by Litong18** [zotify-dev/zotify#25]
I keep on getting these long strings of code when running Zotify. This is what I typed into Powershell:

zotify -l --download-lyrics=True --download-quality=high --md-allgenres=True --skip-existing=true

Then, it showed the following as the download was going on.

 
`incomplete escape \U at position 3

Traceback (most recent call last):
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\site-packages\zotify\track.py", line 190, in download_track
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\site-packages\zotify\track.py", line 190, in <listcomp>
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 539, in _parse
    code = _escape(source, this, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tong\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 393, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 3`

**Comment by Bwall95** [comment]
My guess. Incomplete escape is usually something wrong with your config file.

Download locations need to use "/" instead of "\" for some reason in the .config file. Example:

"ROOT_PATH": "C:/users/Bwall/Downloads/Zotify", (where you want your downloads to go.

I edited the .config file instead of using command line switches and have had more luck.
