### ISSUE TITLE
incomplete escape \U at position 3

### ISSUE THREAD

**Issue by kenny070287** [zotify-dev/zotify#38]
having this issue when downloading from this link: https://open.spotify.com/album/7D2DrBRs922elDgsyNrqjA?si=GZAHGHmhTwOe6j2bozmutQ

```
incomplete escape \U at position 3

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\zotify\track.py", line 190, in download_track
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\zotify\track.py", line 190, in <listcomp>
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\_parser.py", line 539, in _parse
    code = _escape(source, this, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\re\_parser.py", line 393, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 3
```

**Comment by famousfive1** [comment]
I am facing the same problem. I tried removing those failed entries from .song_ids and .song_archive but no luck.

**Comment by pettaa123** [comment]
same issue here with

**Comment by shinji257** [comment]
I've hit into this.  Here is an example of an album that might trigger it...
00vb6sViDbJLmLLchfbRh4
```
bad escape \M at position 3

Traceback (most recent call last):
  File "C:\Users\shinj\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 190, in download_track
    c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\_parser.py", line 544, in _parse
    code = _escape(source, this, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shinj\scoop\apps\python\current\Lib\re\_parser.py", line 443, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \M at position 3
```
Ends up happening on track 2 for this one for me but it might be different for others.  If it triggers it does so consistently.  What I usually end up doing is adding `--root-path .` so that it tries to the current folder then it works just fine.  I'll move that folder to where it is supposed to go and it doesn't give any fits moving either.

**Comment by LylianProgrammer** [comment]
> i had a few escape \M problems with the same line from your traceback. try to replace this in track.py (line 190): `c = len([file for file in Path(filedir).iterdir() if re.search(f'^{filename}_', str(file))]) + 1` with: `c = len([file for file in Path(filedir).iterdir() if re.search(fr'^{re.escape(str(filename))}_', str(file))]) + 1`

Bro thank you so much, this did it for me!

**Comment by kenny070287** [comment]
https://github.com/zotify-dev/zotify/blob/main/INSTALLATION.md

i used Scoop to install zotify based on this link, how do i find the `track.py`? thanks!
