### ISSUE TITLE
i signed up my spotify using google 

### ISSUE THREAD

**Issue by peyman-hakemi** [zotify-dev/zotify#43]
i signed up my spotify using google  and this way i dont have a password
so i created a password

but when i am putting my username and password
it returns this error

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\moham\AppData\Roaming\Python\Python311\Scripts\zotify.exe\__main__.py", line 7, in <module>
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\zotify\__main__.py", line 64, in main
    args.func(args)
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\zotify\app.py", line 21, in client
    Zotify(args)
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\zotify\zotify.py", line 21, in __init__
    Zotify.login(args)
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\zotify\zotify.py", line 46, in login
    cls.SESSION = Session.Builder(conf).user_pass(user_name, password).create()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "C:\Users\moham\AppData\Roaming\Python\Python311\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: TravelRestriction`

**Comment by liamharper2453** [comment]
Possibly this: https://support.spotify.com/uk/article/cant-log-in-abroad/

Your error at the end says 'TravelRestriction'.

**Comment by zotify-dev** [comment]
"TravelRestriction" indicates you're trying to login from a different region than the one your account is set to. See [here](https://support.spotify.com/uk/article/country-region-settings/) or try using a VPN to spoof your location.

**Comment by shinji257** [comment]
You should be able to login to your account on the spotify site and reset your password.  You can then use the username listed on the site profile page with zotify along with the password you just set.  I believe you can also still use your google account to login if I recall correctly.
