### ISSUE TITLE
"Failed fetching audio key" error

### ISSUE THREAD

**Issue by pketh** [zotify-dev/zotify#60]
Recently when I try and download an album or song I get this `GENERAL DOWNLOAD ERROR` that seems related to a failure to fetch `audio key`s:

```
###   SKIPPING: Ravi Shankar - Offering (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 1SrrZO8GYMR44gNiopTxbS
album_num: 01
artist: Philip Glass
album: Passages
album_id: 2PD9WIFJ91puhlzPPkcU6I


Failed fetching audio key! gid: 3db5715f0301495db6c0b43c5856f83c, fileId: d63771a1d7db80f8ca12bd4856ca2621887e9c8a

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/zotify/track.py", line 224, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/zotify/zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/librespot/audio/__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: 3db5715f0301495db6c0b43c5856f83c, fileId: d63771a1d7db80f8ca12bd4856ca2621887e9c8a
```

**Comment by pketh** [comment]
I've also tried reinstalling zotify with the pip commands in the instructions file but that didn't make a difference

**Comment by pketh** [comment]
oh this was related to my spotify account expiring

**Comment by emeaangulo** [comment]
hello! my spotify account is completely useful and I still have the problem is shown on this thread. Could anyone offer some solution for that?

`ID(s): 1
        [∙∙∙] Preparing download... Audio key error, code: 1
        [∙∙●] Preparing download... Audio key error, code: 1
###   SKIPPING: Delaporte - Cariñito (GENERAL DOWNLOAD ERROR)   ###
Track_ID: 5GmB4sjkog7ETZP7KHMa9L


Failed fetching audio key! gid: babc3cfd0015455f937d2d18a6a14335, fileId: 9a93bd939012b6c4c1199ff9637fa7a5a410b930

Traceback (most recent call last):
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\track.py", line 224, in download_track
    stream = Zotify.get_content_stream(track, Zotify.DOWNLOAD_QUALITY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\zotify\zotify.py", line 53, in get_content_stream
    return cls.SESSION.content_feeder().load(content_id, VorbisOnlyAudioQuality(quality), False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 739, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 800, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 754, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 339, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\migue\AppData\Local\pipx\pipx\venvs\zotify\Lib\site-packages\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: babc3cfd0015455f937d2d18a6a14335, fileId: 9a93bd939012b6c4c1199ff9637fa7a5a410b930`
