### ISSUE TITLE
Error with NonType Object

### ISSUE THREAD

**Issue by Happyfeet748** [zotify-dev/zotify#95]
I keep encountering a NonType Object error persistently. I've gone through multiple reinstallation attempts of Zotify, tested it on a Windows VM, my Windows laptop, and another Mac, yet the issue remains consistent across platforms. Despite trying different Spotify accounts, I'm uncertain about the root cause of the problem.

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/zotify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zotify/app.py", line 52, in client
    download_from_user_playlist()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zotify/playlist.py", line 81, in download_from_user_playlist
    download_playlist(playlist)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/zotify/playlist.py", line 52, in download_playlist
    playlist_songs = [song for song in get_playlist_songs(playlist[ID]) if song[TRACK][ID]]
                                                                           ~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable`

**Comment by iMGMoosic** [comment]
Can you explain what fixed this issue? Having the same problem running the latest update.

**Comment by yodaluca23** [comment]
Same @Happyfeet748
